---

- hosts: all
  vars:
    ansible_winrm_user: Administrator
    ansible_winrm_password: packerpassword
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    accounts:
      user:
        groups:
          - administrators
        update_password: always
  roles:
    - win_users
  tasks:
    - name: Firewall rule to allow RDP on TCP port 3389
      community.windows.win_firewall_rule:
        name: Remote Desktop
        localport: 3389
        action: allow
        direction: in
        protocol: tcp
        profiles:
          - domain
          - private
          - public
        state: present
    - name: Accept RDP connections
      ansible.windows.win_powershell:
        script: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name 'fDenyTSConnections' -Value 0
    - name: Enable Remote Dekstop Service
      win_service:
        name: TermService
        start_mode: auto

- hosts: all
  vars:
    ansible_winrm_user: user
    ansible_winrm_password: "{{ lookup('password', 'credentials/user_initial_password chars=ascii_letters,digits length=32') }}"
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
  roles:
    - win_disable_administrator
    - win_rename

